# Generated by Django 4.2.2 on 2023-08-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_boardpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='hashtags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.hashtag'),
        ),
    ]
