# Generated by Django 4.2.2 on 2023-08-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_boardpost_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='boardpost',
            name='title',
        ),
    ]
